spring.application.name=demo

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#(helps avoid dialect issues in Boot 4)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect